### PR TITLE
Fix microphone user experience

### LINKED ISSUE #111: Fail to join room without a microphone connected
**Describe the bug**
A user reported an issue where they tried to join the room without a microphone connection. They received the following error:

`Uncaught (in promise) DOMException: Requested device not found`

With a microphone connected the user stated that they were able to enter the room.

**To Reproduce**
TODO

**Expected behavior**
The user should enter the room or an error should be displayed if it still fails

**Screenshots**
N/A

**Desktop (please complete the following information):**
Chrome via flatpak on Linux

**Additional context**
None

### LINKED ISSUE #163: Allow for room joins without first providing microphone permission
**Describe the bug**

I was curious enough to log in, but when it asks for microphone permission, i'm too scared to proceed.

**To Reproduce**
1. Go to https://thirdroom.io/world/#thirdroom-public:matrix.org
2. Click on 'Enter World'
3. Site asks for permission to use microphone
4. Being scared

**Expected behavior**

To be an inclusive and accessible social space, the software should empower users to participate in a safe and non-overwhelming way, even when they have social anxiety or other social problems.

An option to join muted, like voice chats such as Jitsi Meet have, would help me in this situations, so i can first check out the world without being forced to speak directly.

Joining a personal space first (like some "Home") would also help to get comfortable with the software without having to interact with other people. You could invite people later to hang out there.

There might be other resources and best practices to create a safe and welcoming onboarding for such social tools. You should coordinate with other efforts like Matrix, the VRChat Community and maybe mental health groups.

Check out these videos about your potential audience:

- https://www.youtube.com/watch?v=4PHT-zBxKQQ
- https://www.youtube.com/watch?v=5v_Dl7i4Bcw

**Screenshots**

**A scary situation**

Screenshot from 2022-08-16 07-11-27

**Desktop:**
 - OS: NixOS 22.05.2397.5c211b47aea
 - Browser: Chrome 104.0.5112.79

### LINKED ISSUE #181: Warn the user loudly if they deny microphone permissions
Apparently if the user denies the mic, WebRTC won't spin up and you can't do datachannels, so the world will appear empty. We should warn loudly if/when that happens.

### PR DESCRIPTION
**Pull request by ajbura**
Fixes #111 
Fixes #163 
Fixes #181 

This PR allow user to join world without mic or permission and also gives option to configure mic permission before/after joining world. When user click to unmute mic it will request for permission and unmute if permission allows else shows dialog with error message (like: mic not found, permission denied or other).

### CODE REVIEW

**Comment by ajbura** [comment]
One specific issue i noticed is: sometimes when two person join a world with mic off they don't see each other (It happen randomly and i was not able to find the pattern or why it happens). so this is something we need to make sure of before merging.

**Comment by robertlong** [comment]
Hmm, yeah I was able to reproduce this on my first try. Subsequent tries have worked though.

**Comment by robertlong** [comment]
Screen Shot 2022-08-31 at 11 58 50 AM

Seeing this message in Firefox 104

**Comment by robertlong** [comment]
I don't actually think this bug we're running into with the avatars not spawning is related to this PR. There are active peer connections established which you can verify in the member list or console under `thirdroom.hydrogen.client.callHandler`

Screen Shot 2022-09-01 at 12 45 49 PM

We should merge this PR and follow up on this issue in https://github.com/matrix-org/thirdroom/issues/223

File: src/ui/hooks/usePermissionState.ts [hunk 1]
```diff
@@ -0,0 +1,69 @@
...
+      // eslint-disable-next-line @typescript-eslint/ban-ts-comment
+      // @ts-ignore https://github.com/microsoft/TypeScript/issues/33923
+      .query({ name })
+      .then((permStatus: PermissionStatus) => {
+        permissionStatus = permStatus;
+        handlePermissionChange.apply(permStatus);
+        permStatus.addEventListener("change", handlePermissionChange);
+      })
+      .catch((err) => {
+        console.error(err);
```
Comment (robertlong) [inline src/ui/hooks/usePermissionState.ts:60]: I think we should change this to a warning since Firefox doesn't support this API and it'll still work without it.

**Review by robertlong — APPROVED** [review]
Looks great!

**Comment by robertlong** [comment]
Hmm, while testing with FF and Chrome I'm still running into a lot of edge cases with trying to connect. Definitely worse than what is currently live. I think this still needs some work.

**Review by robertlong — APPROVED** [review]
Should be good now. We'll revisit the remaining bits post Tech Preview launch
