### PR TITLE
Fix back forward history

### LINKED ISSUE #563: Forward / Back History Stack Should Contain Entered World States
When you browse between worlds and hit the browser back button it now adds an item to the history stack where you are not entered into the world.

For example I navigate to Room A then enter then Room B then enter. The history should only contain items for Room A and Room B. Currently there are items for Room A (Unentered), Room A (Entered), Room B (Unentered), Room B (Entered).

### PR DESCRIPTION
**Pull request by ajbura**
Fixes #563

Previously we have to `exitWorld` before entering other this was causing the extra history entry. Now `loadWorld` always try cleaning previous world entry so we do not need to call `exitWorld` before entering new.

### CODE REVIEW

File: src/ui/hooks/useWorldLoader.ts [hunk 1]
```diff
@@ -29,24 +30,32 @@ export interface WorldLoader {
...
 
   const loadWorldCallback = useCallback(
     async (world: Room, content: Content) => {
       const roomId = world.id;
 
+      provideMatrixNetworkInterface((matrixNetworkInterface) => {
+        matrixNetworkInterface?.dispose();
+      });
+      disposeActiveMatrixRoom(mainThread);
+
```
Comment (NateTheGreatt) [inline src/ui/hooks/useWorldLoader.ts:58]: Did some testing and it seems that this addition of code is what broke in-world reloading. When uncommented, in-world reloading works again.

Instead, we should be calling `exitWorldCallback` outside of this file somewhere, for the case that you added these lines in for.

**Review by NateTheGreatt — APPROVED** [review]
tested it out and is all good now, great work!
